name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Basic Tests
      run: |
        python -c "import pandas, numpy, sklearn, fastapi, streamlit"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t loan-api .